// English UI chrome strings (window.TS_UI). The page shell is language-neutral; app.js localizes
// every [data-i18n] / [data-i18n-ph] / [data-i18n-title] hook from this map on load. A localized
// build (e.g. ko/index.html) loads a translated copy of this file instead — same keys, same app.js.
window.TS_UI = {
  // header
  "header.subtitle": "A build planner & reference for TROUBLESHOOTER: Abandoned Children",

  // top navigation tabs
  "tab.masteries": "Masteries",
  "tab.individual": "Individual",
  "tab.npc": "NPC / Promotion",
  "tab.company": "Company",
  "tab.modules": "Modules",
  "tab.classTraits": "Class Traits",
  "tab.misc": "Misc",
  "tab.sets": "Mastery Sets",
  "tab.equipsets": "Equipment Sets",
  "tab.abilities": "Abilities",
  "tab.dialogue": "Dialogue",
  "tab.quests": "Quests",
  "tab.builder": "Board Builder",

  // search + filters
  "search.placeholder": "Search…",
  "search.clear": "Clear search",
  "filter.type": "Type",
  "filter.category": "Category",
  "filter.all": "All",
  "filter.allShort": "*",
  "case.tooltip": "{case} Case",
  "case.Scenario": "Scenario",
  "case.Quest": "Requested",
  "case.Ordinary": "Ordinary",
  "case.Violent": "Violent",
  "colfilter.placeholder": "Filter…",
  "colfilter.clear": "Clear filter",
  "srcfilter.enemies": "Enemies",
  "srcfilter.characters": "Characters",
  "srcfilter.jobs": "Jobs",
  "srcfilter.beasts": "Beasts",
  "srcfilter.drones": "Drones",
  "srcfilter.achievement": "Achievement",
  "srcfilter.story": "Story",
  "srcfilter.initial": "From start",
  "srcfilter.research": "Research",
  "filter.starred": "Starred",
  "filter.starredTitle": "Show only starred masteries",

  // mastery-table character sub-tabs
  "subtab.troubleshooter": "Troubleshooter",
  "subtab.beast": "Beast",
  "subtab.machine": "Drone / Machine",

  // mastery-table column headers
  "th.name": "Name",
  "th.description": "Description",
  "th.character": "Character",
  "th.type": "Type",
  "th.category": "Category",
  "th.cost": "Cost",
  "th.cost.title": "Training-point / Output cost",
  "th.sets": "Sets",
  "th.sources": "Sources",

  // ability-table column headers
  "th.slot": "Slot",
  "th.element": "Element",
  "th.apCost": "Cost",
  "th.apCost.title": "Action cost",
  "th.cooldown": "CD",
  "th.cooldown.title": "Cooldown (turns)",
  "th.cast": "Cast",
  "th.cast.title": "Cast delay",

  // board builder — build management
  "bld.builds": "Builds",
  "bld.new": "+ New",
  "bld.new.title": "Start a new empty build",
  "bld.duplicate": "Duplicate",
  "bld.duplicate.title": "Duplicate this build",
  "bld.rename": "Rename",
  "bld.rename.title": "Rename this build",
  "bld.delete": "Delete",
  "bld.delete.title": "Delete this build",

  // board builder — character bar
  "bld.character": "Character",
  "bld.class": "Class",       // 2nd selector label for a PC (swapped to Form / SP at runtime)
  "bld.form": "Form",         // … for a beast
  "bld.sp": "SP",             // … for a drone
  "bld.os": "OS",
  "bld.osGroup": "Operating System",
  "bld.reinforce": "Reinforce",
  "bld.level": "Level",
  "bld.import": "Import",
  "bld.import.title": "Import a build (share code/link) or restore a backup",
  "bld.exportall": "Backup",
  "bld.exportall.title": "Download all your builds (and starred masteries) as a backup file",
  "bld.export": "Export",
  "bld.export.title": "Share this build — in-game code + link",

  // ---- dynamic strings built in app.js (localized via t() / tf() with {placeholders}) ----
  // result counts + empty states
  "group.normal": "masteries",
  "group.individual": "individual masteries",
  "group.npc": "NPC / promotion masteries",
  "group.company": "company masteries",
  "group.module": "drone modules",
  "group.class": "class traits",
  "group.misc": "misc masteries",
  "count.shown": "{n} of {total} {label}",
  "count.sets": "{n} of {total} sets",
  "count.equipsets": "{n} of {total} equipment sets",
  "count.abilities": "{n} of {total} abilities",
  "count.dialogues": "{n} of {total} dialogue stages",
  "count.quests": "{n} of {total} quests",
  "empty.masteries": "No masteries match.",
  "empty.starred": "No starred masteries — click ☆ on a row to track one.",
  "empty.sets": "No sets match.",
  "empty.equipsets": "No equipment sets match.",
  "empty.abilities": "No abilities match.",
  "empty.dialogues": "No dialogue stages match.",
  "empty.quests": "No quests match.",
  "quest.unlockAfter": "Unlocks after",
  "quest.requires": "Requires",
  "quest.dropFrom": "Drops from",
  "quest.chooseOne": "Choose one of:",
  "quest.friendship": "+{n} Friendship",
  "quest.unlocksJointDrill": "Unlocks Joint Drill",
  "reward.recipe": "Recipe: {name}",
  "reward.troublemaker": "{n}× {pool} Troublemaker info",
  "reward.workmanship": "{pool} workmanship +{n}",
  "dlg.decisions1": "{n} decision",
  "dlg.decisionsN": "{n} decisions",
  "dlg.grants": "Grants {name}",
  "equip.pieces": "{n} pc",
  "src.enemy": "{n} enemy",
  "src.enemies": "{n} enemies",
  "src.characters": "{n} character",
  "src.jobs": "{n} job",
  "src.beasts": "{n} beast",
  "src.drones": "{n} drone",
  "src.achievement": "achievement",
  "src.story": "story",
  "src.initial": "from start",
  "src.research": "research",
  "footer.credit": "All game data is extracted from TROUBLESHOOTER: Abandoned Children and remains the property of Dandylion. Thank you for making such a wonderful game and supporting the community.",

  // mastery row detail
  "detail.beastEvo": "Beast evolution mastery",
  "detail.achievement": "Unlocked by an achievement (in-game feat)",
  "detail.achGeneric": "An in-game feat",
  "detail.story": "Unlocked by a story mission",
  "detail.initial": "Available from the start",
  "detail.initialLine": "Unlocked by default — no research or analysis needed.",
  "detail.research": "Unlocked by mastery research",
  "detail.researchLine": "Unlocks after crafting",
  "detail.storyChoice": "{mission} — choose “{choice}”",
  "detail.storyReward": "{mission} (mission reward)",
  "detail.storyTutorial": "{mission} (tutorial)",
  "detail.charUnlock": "Unlocked by levelling a character in a job",
  "detail.charBasic": "Granted with a character’s class",
  "detail.charBasicLine": "{character} as {job}",
  "detail.beastUnlock": "Unlocked by capturing & levelling a beast",
  "detail.droneUnlock": "Unlocked by building & levelling a drone",
  "detail.enemies": "Learnable from enemies ({n})",
  "detail.job": "Job",
  "detail.noSource": "No source data (learned via story, quest or class change).",
  "detail.charLine": "{character} as {job} — Lv {lv}",
  "detail.lvLine": "{name} — Lv {lv}",
  "detail.jointTraining": "⚔ Joint Drill",
  "detail.moreEnemies": "+{n} more",
  "detail.grantsAbility": "Grants ability:",

  // beast-availability section headers + evolution-source lines, owner-column sentinels, drone fallback
  "owner.promotion": "Promotion",
  "owner.anyBeast": "Any beast",
  "owner.anyBeastGenetic": "Any beast (genetic modification)",
  "avail.species": "Species — {family}",
  "avail.speciesMulti": "Species — several families",
  "avail.global": "Any beast",
  "avail.element": "Element-locked",
  "avail.genetic": "Genetic modification",
  "avail.other": "Other",
  "section.other": "Other",
  "src.offeredBy": "Offered by {n} form(s){group}:",
  "src.formStage": "• {name} (stage {stage})",
  "src.beastGlobal": "Any captured beast can roll this at an evolution.",
  "src.beastElement": "Only {element}-element beasts can roll this.",
  "src.beastGenetic": "Available to any beast via genetic modification.",
  "src.beastEvoPick": "An evolution-stage pick (1 of 3 offered).",
  "src.beastRepick": "Re-pickable later (changeable pool).",

  // ability row detail + slot/stat labels
  "detail.abilityGranted": "Granted by masteries",
  "detail.abilityModified": "Modified by masteries",
  "detail.abilityOwners": "Available to",
  "ability.slot.basic": "Basic",
  "ability.slot.normal": "Normal",
  "ability.slot.ultimate": "Ultimate",
  "ability.slot.potion": "Potion",
  "ability.slot.grenade": "Grenade",
  "ability.slot.spray": "Spray",
  "ability.slot.device": "Device",
  "ability.slot.mastery": "Mastery",
  "ability.self": "Self",
  "ability.range": "Range {n}",
  "ability.targets": "{n} targets",
  "ability.sp": "{n} SP",
  "ability.hit": "{type} hit",
  "ability.damageAmount": "X",   // placeholder for the runtime, unit-dependent $DamageAmount$
  "buff.moreMembers": "+{n} more",

  // board builder — board, slots, panels, sidebar
  "bld.pickCharacter": "Pick a character to start building a mastery board.",
  "bld.none": "— none —",
  "bld.pickCharacterShort": "— pick a character —",
  "bld.evoMasteries": "Evolution masteries",
  "bld.evoElement": "Element",
  "bld.evoSpecies": "Species",
  "bld.craftAi": "Craft & AI upgrades",
  "bld.machineCrafting": "Machine Crafting",
  "bld.slotEmpty": "Empty",
  "bld.slotLocked": "Unlock Lv {lv}",
  "bld.slotRemove": "Remove",
  "bld.slotFixed": "Inherent to this character — always present",
  "bld.colFilterTitle": "Filter the sidebar to {label} masteries",
  "bld.costTitle": "Training-point cost used / cap",
  "bld.summary": "Training Point {used}/{total}",
  "bld.broken": "⚠ Build broken — ",
  "bld.brokenSlots": "{label}: {n} masteries over {cap} unlocked slots",
  "bld.brokenCost": "{label}: {n} points over {cap} cost cap",
  "bld.brokenTotal": "Total: {n} points over {cap} cap",
  "bld.masterySet": "Mastery Set",
  "bld.noSets": "No matching sets",
  "bld.addMissing": "Add the missing masteries to the build",
  "bld.missing": "Missing {k}",
  "bld.missingComplete": " — click to complete",
  "bld.sideMasteries": "Masteries",
  "bld.sideSets": "Sets",
  "bld.sideFilter": "Filter…",
  "bld.accessibleMasteries": "{n} accessible masteries",
  "bld.accessibleSets": "{n} accessible sets",
  "bld.catFiltered": "{n} {label} masteries · show all ✕",
  "bld.itemMeta": "{cat} · {cost}",

  // builds management (prompts + default names)
  "bld.renamePrompt": "Build name:",
  "bld.deleteConfirm": "Delete build \"{name}\"?",
  "bld.defaultName": "My build",
  "bld.buildWord": "Build",
  "bld.newName": "Build {n}",
  "bld.copySuffix": " copy",
  "bld.sharedName": "{name} (shared)",

  // import / export panel
  "io.placeholder": "Paste a board share code (e.g. KSAAC…), a share link, or a TroubleMaster export here…",
  "io.import": "Import",
  "io.merged": "Imported {added} build(s); {dup} duplicate(s) skipped; {stars} starred added.",
  "io.partialWarn": "{unknown} of {total} masteries weren’t recognized (a newer game version?) and will be left off.",
  "io.importPartial": "Import the {known} recognized",
  "io.copied": "Copied ✓",
  "io.copyFailed": "Copy failed",
  "io.pickFirst": "Pick a character first.",
  "io.shareCode": "In-game share code:",
  "io.copyCode": "Copy code",
  "io.copyLink": "Copy link",
  "io.copyLinkTitle": "A shareable URL that opens this build in the builder",
  "io.linkRestoresNote": "The in-game code is board-only, so it imports into the game; the share link also restores the picks it can't carry — a beast's evolution masteries, or a drone's OS / reinforcement / craft & AI-upgrade picks.",
  "io.errEmpty": "Nothing to import — paste a code, link, or export.",
  "io.errDecode": "Couldn't decode that as a board share code or link.",
  "io.errJson": "Invalid JSON: ",
  "io.errFormat": "Unrecognized format — expected a TroubleMaster export (use “Backup”).",
};
