// Korean UI chrome strings (window.TS_UI). Same keys as ui.en.js — loaded by ko/index.html.
// In-game Korean terms used where the game has one (특성 = mastery,
// 특성판 = mastery board, 추가 특성 = mastery set, 모듈 = module, 클래스 = class, 코스트 = cost,
// 종류 = type, 운영체제 = OS, 승격 = promotion, 대사 = dialogue, 트러블슈터, 야수, 드론 …).
window.TS_UI = {
  // header
  "header.subtitle": "트러블슈터: 버려진 아이들 빌드 플래너 & 참고 자료",

  // top navigation tabs
  "tab.masteries": "특성",
  "tab.individual": "개인",
  "tab.npc": "NPC / 승격",
  "tab.company": "회사",
  "tab.modules": "모듈",
  "tab.classTraits": "클래스 특성",
  "tab.misc": "기타",
  "tab.sets": "추가 특성",
  "tab.equipsets": "장비 세트",
  "tab.items": "아이템",
  "filter.rarity": "등급",
  "filter.level": "레벨",
  "itemcat.weapon": "무기",
  "itemcat.weaponNpc": "NPC 무기",
  "itemcat.armor": "방어구",
  "itemcat.accessory": "악세서리",
  "itemcat.consume": "소모품",
  "itemcat.material": "소재",
  "itemcat.tool": "도구",
  "itemcat.machine": "기계",
  "itemcat.machineNpc": "NPC 기계",
  "itemcat.etc": "기타",
  "count.items": "아이템 {total}개 중 {n}개",
  "empty.items": "일치하는 아이템이 없습니다.",
  "item.reqlv": "Lv {n}",
  "item.grantsAbility": "어빌리티 부여:",
  "item.effect": "장비 효과",
  "item.partOfSet": "세트:",
  "item.fixedStats": "고정 옵션 — 감정할 수 없습니다.",
  "item.suffixes": "가능한 접미 옵션 ({n})",
  "item.drops": "드롭 ({n})",
  "item.stageLoot": "획득 가능 미션",
  "item.lootBox": "전리품 상자",
  "item.lootBoxNote": "Lv {lv} 스테이지의 전리품 상자에서 획득 ({tier}).",
  "item.craft": "제작",
  "item.craftStarter": "기본 레시피",
  "item.craftUnlock": "{x} 숙련 시 해금",
  "item.craftQuest": "퀘스트 보상 레시피 (퀘스트 탭 참고)",
  "item.craftNoUnlock": "제작 해금 없음 — 다른 방법으로 획득",
  "item.craftRaid": "파스칼의 은신처 습격 이후에만 제작 가능",
  "item.quest": "퀘스트 보상",
  "item.questNote": "퀘스트 보상으로 획득 — 퀘스트 탭 참고.",
  "item.rescue": "시민 구출 보상",
  "item.rescueNote": "시민을 구출하면 우편으로 지급됩니다.",
  "item.steal": "훔치기 (도둑)",
  "item.stealNote": "주머니에 있음 — 도둑(미스티)으로 훔칠 수 있음, 대상:",
  "item.npcOnly": "NPC 전용 장비",
  "item.npcNote": "플레이어 획득 불가 — 착용 NPC:",
  "item.event": "스토리 / 튜토리얼 지급",
  "item.eventNote": "스토리나 튜토리얼 진행 중 지급.",
  "item.shops": "판매처",
  "item.starting": "시작 장비",
  "item.price": "{n} {cur}",
  "item.friendship": "친밀도 {x}",
  "item.noSource": "알려진 획득처 없음.",
  "tab.abilities": "어빌리티",
  "tab.dialogue": "대사",
  "tab.quests": "퀘스트",
  "tab.builder": "특성판 편성",

  // search + filters
  "search.placeholder": "검색…",
  "search.clear": "검색 지우기",
  "filter.type": "종류",
  "filter.category": "카테고리",
  "filter.all": "전체",
  "filter.allShort": "*",
  "case.tooltip": "{case} 사건",
  "case.Scenario": "시나리오",
  "case.Quest": "의뢰",
  "case.Ordinary": "일반",
  "case.Violent": "강력",
  "colfilter.placeholder": "필터…",
  "colfilter.clear": "필터 지우기",
  "srcfilter.enemies": "적",
  "srcfilter.characters": "캐릭터",
  "srcfilter.jobs": "클래스",
  "srcfilter.beasts": "야수",
  "srcfilter.drones": "드론",
  "srcfilter.achievement": "업적",
  "srcfilter.story": "스토리",
  "srcfilter.initial": "초기 보유",
  "srcfilter.research": "특성 연구",
  "filter.starred": "즐겨찾기",
  "filter.starredTitle": "즐겨찾기한 특성만 보기",

  // mastery-table character sub-tabs
  "subtab.troubleshooter": "트러블슈터",
  "subtab.beast": "야수",
  "subtab.machine": "드론 / 기계",

  // mastery-table column headers
  "th.name": "이름",
  "th.description": "설명",
  "th.character": "캐릭터",
  "th.type": "종류",
  "th.category": "카테고리",
  "th.cost": "코스트",
  "th.cost.title": "특성 코스트 / 드론 출력 비용",
  "th.sets": "세트",
  "th.sources": "획득처",

  // 어빌리티 표 열 머리글
  "th.slot": "슬롯",
  "th.element": "속성",
  "th.apCost": "소모",
  "th.apCost.title": "행동 소모",
  "th.cooldown": "재사용",
  "th.cooldown.title": "재사용 대기시간 (턴)",
  "th.cast": "시전",
  "th.cast.title": "시전 지연",

  // board builder — build management
  "bld.builds": "빌드",
  "bld.new": "+ 새 빌드",
  "bld.new.title": "새 빈 빌드 만들기",
  "bld.duplicate": "복제",
  "bld.duplicate.title": "이 빌드 복제",
  "bld.rename": "이름 변경",
  "bld.rename.title": "이 빌드 이름 변경",
  "bld.delete": "삭제",
  "bld.delete.title": "이 빌드 삭제",

  // board builder — character bar
  "bld.character": "캐릭터",
  "bld.class": "클래스",        // 2nd selector label for a PC (swapped to 형태 / 특수 능력 at runtime)
  "bld.form": "형태",           // … for a beast (evolution form)
  "bld.sp": "특수 능력",         // … for a drone (SP structure)
  "bld.os": "운영체제",
  "bld.osGroup": "운영체제",
  "bld.reinforce": "강화",
  "bld.level": "레벨",
  "bld.import": "가져오기",
  "bld.import.title": "빌드 가져오기 (공유 코드/링크) 또는 백업 복원",
  "bld.exportall": "백업",
  "bld.exportall.title": "모든 빌드(및 즐겨찾기한 특성)를 백업 파일로 다운로드",
  "bld.export": "내보내기",
  "bld.export.title": "이 빌드 공유 — 게임 내 코드 + 링크",
  "bld.undo": "실행 취소",
  "bld.undo.title": "이 빌드의 마지막 변경 취소 (Ctrl+Z)",
  "bld.redo": "다시 실행",
  "bld.redo.title": "취소한 변경 다시 실행 (Ctrl+Shift+Z)",

  // ---- 앱에서 동적으로 생성되는 문자열 (t() / tf() + {플레이스홀더}) ----
  // 결과 개수 + 빈 상태
  "group.normal": "특성",
  "group.individual": "개인 특성",
  "group.npc": "NPC / 승격 특성",
  "group.company": "회사 특성",
  "group.module": "드론 모듈",
  "group.class": "클래스 특성",
  "group.misc": "기타 특성",
  "count.shown": "{label} {total}개 중 {n}개",
  "count.sets": "세트 {total}개 중 {n}개",
  "count.equipsets": "장비 세트 {total}개 중 {n}개",
  "count.abilities": "어빌리티 {total}개 중 {n}개",
  "count.dialogues": "대사 {total}개 중 {n}개",
  "count.quests": "퀘스트 {total}개 중 {n}개",
  "empty.masteries": "일치하는 특성이 없습니다.",
  "empty.starred": "즐겨찾기한 특성이 없습니다 — 행의 ☆를 눌러 추적하세요.",
  "empty.sets": "일치하는 세트가 없습니다.",
  "empty.equipsets": "일치하는 장비 세트가 없습니다.",
  "empty.abilities": "일치하는 어빌리티가 없습니다.",
  "empty.dialogues": "일치하는 대사가 없습니다.",
  "empty.quests": "일치하는 퀘스트가 없습니다.",
  "quest.unlockAfter": "선행 미션",
  "quest.requires": "선행",
  "quest.dropFrom": "드롭 대상",
  "quest.chooseOne": "다음 중 하나 선택:",
  "quest.friendship": "우호도 +{n}",
  "quest.unlocksJointDrill": "합동훈련 개방",
  "reward.recipe": "제작법: {name}",
  "reward.troublemaker": "{pool} 정보 {n}개",
  "reward.workmanship": "{pool} 숙련도 +{n}",
  "dlg.decisions1": "결정 {n}개",
  "dlg.decisionsN": "결정 {n}개",
  "dlg.grants": "{name} 획득",
  "dlg.opens": "{name} 연구 해금",
  "equip.pieces": "{n}개",
  "src.enemy": "적 {n}종",
  "src.enemies": "적 {n}종",
  "src.characters": "캐릭터 {n}명",
  "src.jobs": "클래스 {n}개",
  "src.beasts": "야수 {n}종",
  "src.drones": "드론 {n}기",
  "src.achievement": "업적",
  "src.story": "스토리",
  "src.initial": "초기 보유",
  "src.research": "특성 연구",
  "footer.credit": "모든 게임 데이터는 「트러블슈터: 버려진 아이들」에서 추출되었으며 저작권은 댄디라이언에 있습니다. 멋진 게임을 만들고 커뮤니티를 지원해 주셔서 감사합니다.",

  // 특성 상세
  "detail.beastEvo": "야수 진화 특성",
  "detail.achievement": "업적(인게임 도전 과제)으로 습득",
  "detail.achGeneric": "인게임 도전 과제",
  "detail.story": "스토리 미션으로 습득",
  "detail.initial": "초기부터 보유",
  "detail.initialLine": "기본 해금 — 연구나 분석이 필요 없습니다.",
  "detail.research": "특성 연구로 해금",
  "detail.researchLine": "제작 후 해금:",
  "detail.storyChoice": "{mission} — “{choice}” 선택",
  "detail.storyReward": "{mission} (미션 보상)",
  "detail.storyTutorial": "{mission} (튜토리얼)",
  "detail.storyOpened": "(획득하지 못해도 연구로 해금)",
  "detail.charUnlock": "캐릭터 클래스 레벨업으로 습득",
  "detail.charBasic": "캐릭터 클래스 습득 시 지급",
  "detail.charBasicLine": "{character} · {job}",
  "detail.beastUnlock": "야수 포획 후 레벨업으로 습득",
  "detail.droneUnlock": "드론 제작 후 레벨업으로 습득",
  "detail.enemies": "적에게서 습득 가능 ({n})",
  "detail.job": "클래스",
  "detail.noSource": "출처 정보 없음 (스토리 · 퀘스트 · 클래스 변경으로 습득).",
  "detail.charLine": "{character} · {job} Lv {lv}",
  "detail.lvLine": "{name} · Lv {lv}",
  "detail.jointTraining": "⚔ 합동훈련",
  "detail.moreEnemies": "+{n}종 더 보기",
  "detail.grantsAbility": "부여 어빌리티:",
  "detail.moduleCraft": "제작 재료:",

  // 야수 획득 분류 헤더 + 진화 출처 설명, 소유자 칸 기본값, 드론 기타 분류
  "owner.promotion": "승격",
  "owner.anyBeast": "모든 야수",
  "owner.anyBeastGenetic": "모든 야수 (유전자 변형)",
  "avail.species": "종족 — {family}",
  "avail.speciesMulti": "종족 — 여러 계열",
  "avail.global": "모든 야수",
  "avail.element": "속성 제한",
  "avail.genetic": "유전자 변형",
  "avail.other": "기타",
  "section.other": "기타",
  "src.offeredBy": "{n}개 형태에서 제공{group}:",
  "src.formStage": "• {name} ({stage}단계)",
  "src.beastGlobal": "포획한 모든 야수가 진화 시 획득할 수 있습니다.",
  "src.beastElement": "{element} 속성 야수만 획득할 수 있습니다.",
  "src.beastGenetic": "유전자 변형을 통해 모든 야수가 획득할 수 있습니다.",
  "src.beastEvoPick": "진화 단계 선택지입니다 (3개 중 1개 제공).",
  "src.beastRepick": "이후 다시 선택할 수 있습니다 (변경 가능한 풀).",

  // 어빌리티 상세 + 슬롯 / 스탯 라벨
  "detail.abilityGranted": "이 어빌리티를 부여하는 특성",
  "detail.abilityModified": "이 어빌리티를 변경하는 특성",
  "detail.abilityOwners": "사용 가능",
  "ability.slot.basic": "기본",
  "ability.slot.normal": "일반",
  "ability.slot.ultimate": "궁극기",
  "ability.slot.potion": "물약",
  "ability.slot.grenade": "수류탄",
  "ability.slot.spray": "스프레이",
  "ability.slot.device": "장치",
  "ability.slot.mastery": "특성",
  "ability.self": "자신",
  "ability.range": "사거리 {n}",
  "ability.targets": "대상 {n}개",
  "ability.sp": "{n} SP",
  "ability.hit": "{type} 명중",
  "buff.moreMembers": "외 {n}개",

  // 특성판 편성 — 보드 / 슬롯 / 패널 / 사이드바
  "bld.pickCharacter": "특성판을 만들 캐릭터를 선택하세요.",
  "bld.none": "— 없음 —",
  "bld.pickCharacterShort": "— 캐릭터 선택 —",
  "bld.evoMasteries": "진화 특성",
  "bld.evoElement": "속성",
  "bld.evoSpecies": "종족",
  "bld.craftAi": "제작 & AI 강화",
  "bld.machineCrafting": "기계 제작",
  "bld.slotEmpty": "비어 있음",
  "bld.slotLocked": "Lv {lv} 해제",
  "bld.slotRemove": "제거",
  "bld.slotFixed": "이 캐릭터의 고유 특성 — 항상 적용",
  "bld.colFilterTitle": "사이드바를 {label} 특성으로 필터링",
  "bld.costTitle": "사용 코스트 / 한도",
  "bld.summary": "특성 코스트 {used}/{total}",
  "bld.broken": "⚠ 빌드 오류 — ",
  "bld.brokenSlots": "{label}: 특성 {n}개가 해제된 슬롯 {cap}개를 초과",
  "bld.brokenCost": "{label}: 코스트 {n}이(가) 한도 {cap}을(를) 초과",
  "bld.brokenTotal": "전체: 코스트 {n}이(가) 한도 {cap}을(를) 초과",
  "bld.brokenExclusive": "{a}와(과) {b}은(는) 함께 장착할 수 없습니다",
  "bld.switchConfirm": "전환하면 새 형태 또는 직업이 장착할 수 없는 특성 {n}개가 제거됩니다:\n\n{list}\n\n전환하시겠습니까?",
  "bld.masterySet": "추가 특성",
  "bld.noSets": "완성된 세트 없음",
  "bld.sideMasteries": "특성",
  "bld.sideSets": "세트",
  "bld.sideFilter": "필터…",
  "bld.fit": "적합",
  "bld.fitTitle": "여유 슬롯과 코스트 한도에 맞는 특성만 표시",
  "bld.accessibleMasteries": "사용 가능한 특성 {n}개",
  "bld.accessibleSets": "사용 가능한 세트 {n}개",
  "bld.catFiltered": "{label} 특성 {n}개 · 전체 보기 ✕",
  "bld.itemMeta": "{cat} · {cost}",

  // 빌드 관리 (프롬프트 + 기본 이름)
  "bld.renamePrompt": "빌드 이름:",
  "bld.deleteConfirm": "\"{name}\" 빌드를 삭제할까요?",
  "bld.defaultName": "내 빌드",
  "bld.buildWord": "빌드",
  "bld.newName": "빌드 {n}",
  "bld.copySuffix": " 복제본",
  "bld.sharedName": "{name} (공유됨)",

  // 가져오기 / 내보내기 패널
  "io.placeholder": "특성판 공유 코드(예: KSAAC…), 공유 링크, 또는 TroubleMaster 내보내기를 여기에 붙여넣으세요…",
  "io.import": "가져오기",
  "io.merged": "빌드 {added}개 가져옴; 중복 {dup}개 건너뜀; 즐겨찾기 {stars}개 추가됨.",
  "io.partialWarn": "특성 {total}개 중 {unknown}개를 인식할 수 없어(더 최신 게임 버전?) 제외됩니다.",
  "io.importPartial": "인식된 {known}개 가져오기",
  "io.copied": "복사됨 ✓",
  "io.copyFailed": "복사 실패",
  "io.pickFirst": "먼저 캐릭터를 선택하세요.",
  "io.shareCode": "게임 내 공유 코드:",
  "io.copyCode": "코드 복사",
  "io.copyLink": "링크 복사",
  "io.copyLinkTitle": "이 빌드를 편성기에서 여는 공유 URL",
  "io.linkRestoresNote": "게임 내 코드는 보드 전용이라 게임으로 가져올 수 있습니다; 공유 링크는 코드가 담지 못하는 선택 — 비스트의 진화 특성, 드론의 운영체제 / 강화 단계 / 제작 & AI 강화 선택 — 까지 복원합니다.",
  "io.errEmpty": "가져올 내용이 없습니다 — 코드, 링크, 또는 내보내기를 붙여넣으세요.",
  "io.errDecode": "특성판 공유 코드나 링크로 해석할 수 없습니다.",
  "io.errJson": "잘못된 JSON: ",
  "io.errFormat": "인식할 수 없는 형식 — TroubleMaster 내보내기가 필요합니다 (\"백업\" 사용).",
};
